"""Cloudflare OAuth2/OIDC login helpers (authorization-code + PKCE flow).

Talks to the Cloudflare OAuth issuer (`settings.cf_oauth_issuer`) for the
authorize/token/userinfo/jwks endpoints, and to the Cloudflare API
(`settings.upstream_base_url`) to discover the DNS-edit scope literal.
"""

import base64
import hashlib
import hmac
import secrets
import time
from typing import Any
from urllib.parse import urlencode

import httpx
import jwt
from jwt.algorithms import RSAAlgorithm

from cfproxy.config import get_settings

_ALLOWED_ALGS = ["RS256"]
_JWKS_CACHE_TTL_SECONDS = 3600

_jwks_cache: dict[str, Any] | None = None
_jwks_cache_fetched_at: float = 0.0


def make_pkce() -> tuple[str, str]:
    """Generate a PKCE code verifier and its S256 code challenge.

    Return:
        pair(tuple[str, str]): `(verifier, s256_challenge)` per RFC 7636.
    """
    verifier = secrets.token_urlsafe(64)
    digest = hashlib.sha256(verifier.encode()).digest()
    challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode()
    return verifier, challenge


def build_authorize_url(state: str, nonce: str, code_challenge: str) -> str:
    """Build the Cloudflare OAuth authorize URL for the login redirect.

    Args:
        state(str): Opaque anti-CSRF state value, stored server-side.
        nonce(str): Per-login nonce, echoed back inside the id_token.
        code_challenge(str): PKCE S256 code challenge derived from the verifier.

    Return:
        url(str): Fully-qualified `/oauth2/auth` URL with all required query params.
    """
    settings = get_settings()
    scopes = settings.cf_oauth_base_scopes
    if settings.cf_oauth_dns_scope:
        scopes = f"{scopes} {settings.cf_oauth_dns_scope}"
    params = {
        "response_type": "code",
        "client_id": settings.cf_oauth_client_id,
        "redirect_uri": settings.cf_oauth_redirect_uri,
        "scope": scopes,
        "state": state,
        "nonce": nonce,
        "code_challenge": code_challenge,
        "code_challenge_method": "S256",
    }
    return f"{settings.cf_oauth_issuer}/oauth2/auth?{urlencode(params)}"


async def exchange_code(code: str, code_verifier: str) -> dict:
    """Exchange an authorization code for tokens.

    Args:
        code(str): The authorization code returned to the callback.
        code_verifier(str): The PKCE verifier generated by `make_pkce`.

    Return:
        tokens(dict): Parsed token response (access_token, id_token, refresh_token, etc.).
    """
    settings = get_settings()
    data = {
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": settings.cf_oauth_redirect_uri,
        "client_id": settings.cf_oauth_client_id,
        "client_secret": settings.cf_oauth_client_secret,
        "code_verifier": code_verifier,
    }
    async with httpx.AsyncClient() as client:
        response = await client.post(f"{settings.cf_oauth_issuer}/oauth2/token", data=data)
    response.raise_for_status()
    return response.json()


async def refresh_access_token(refresh_token: str) -> dict:
    """Refresh an access token using a stored refresh token.

    Args:
        refresh_token(str): The refresh token previously issued by Cloudflare.

    Return:
        tokens(dict): Parsed token response (access_token, possibly rotated refresh_token, etc.).
    """
    settings = get_settings()
    data = {
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
        "client_id": settings.cf_oauth_client_id,
        "client_secret": settings.cf_oauth_client_secret,
    }
    async with httpx.AsyncClient() as client:
        response = await client.post(f"{settings.cf_oauth_issuer}/oauth2/token", data=data)
    response.raise_for_status()
    return response.json()


async def fetch_jwks() -> dict:
    """Fetch the issuer's JWKS document, caching it in-process.

    Return:
        jwks(dict): The JSON Web Key Set document (`{"keys": [...]}`).
    """
    global _jwks_cache, _jwks_cache_fetched_at
    now = time.monotonic()
    if _jwks_cache is not None and (now - _jwks_cache_fetched_at) < _JWKS_CACHE_TTL_SECONDS:
        return _jwks_cache
    settings = get_settings()
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{settings.cf_oauth_issuer}/.well-known/jwks.json")
    response.raise_for_status()
    _jwks_cache = response.json()
    _jwks_cache_fetched_at = now
    return _jwks_cache


def clear_jwks_cache() -> None:
    """Clear the in-process JWKS cache (used by tests to force a re-fetch)."""
    global _jwks_cache, _jwks_cache_fetched_at
    _jwks_cache = None
    _jwks_cache_fetched_at = 0.0


async def _resolve_signing_key(kid: str | None) -> Any:
    """Resolve the RSA public key matching `kid` from the cached JWKS.

    Args:
        kid(str | None): The `kid` header claim from the id_token, if present.

    Return:
        key(Any): The RSA public key object usable by `jwt.decode`.
    """
    jwks = await fetch_jwks()
    keys = jwks.get("keys", [])
    matches = [k for k in keys if kid is None or k.get("kid") == kid]
    if not matches:
        clear_jwks_cache()
        jwks = await fetch_jwks()
        keys = jwks.get("keys", [])
        matches = [k for k in keys if kid is None or k.get("kid") == kid]
    if not matches:
        raise jwt.InvalidTokenError("No matching JWKS key found for id_token kid")
    return RSAAlgorithm.from_jwk(matches[0])


def _compute_oidc_hash(value: str, alg: str) -> str:
    """Compute the OIDC `at_hash`/`c_hash` value for `value` under `alg`.

    Per OpenID Connect Core 3.1.3.6: hash the ASCII octets of the value with
    the hash algorithm paired to the id_token's signing alg (SHA-256 for
    RS256), take the left-most half of the digest, and base64url-encode it
    without padding.

    Args:
        value(str): The access token (for `at_hash`) or authorization code
            (for `c_hash`) to hash.
        alg(str): The id_token signing algorithm (e.g. "RS256").

    Return:
        half_hash(str): The base64url (unpadded) left-half hash.

    Raises:
        jwt.InvalidTokenError: If `alg` has no supported hash pairing.
    """
    if alg == "RS256":
        digest = hashlib.sha256(value.encode("ascii")).digest()
    else:
        raise jwt.InvalidTokenError(f"No OIDC hash pairing for alg: {alg!r}")
    half = digest[: len(digest) // 2]
    return base64.urlsafe_b64encode(half).rstrip(b"=").decode("ascii")


async def validate_id_token(
    id_token: str,
    nonce: str,
    *,
    access_token: str | None = None,
    code: str | None = None,
) -> dict:
    """Strictly validate a Cloudflare OIDC id_token and return its claims.

    Verifies (in order): algorithm allowlist (RS256 only; rejects `none`/HS*),
    signature via the issuer's cached JWKS, `iss`, `aud`, `exp`/`iat`/`nbf`
    (within `settings.access_token_skew`), and the `nonce` claim against the
    caller-supplied value. When present, `at_hash` is cryptographically
    verified against `access_token` and `c_hash` against `code` using the OIDC
    left-half-hash construction and a constant-time comparison.

    Args:
        id_token(str): The encoded JWT id_token from the token endpoint.
        nonce(str): The nonce that was sent in the original authorize request.
        access_token(str, optional): The access token returned alongside the
            id_token, required to verify `at_hash` when that claim is present.
        code(str, optional): The authorization code, required to verify
            `c_hash` when that claim is present.

    Return:
        claims(dict): The validated id_token claims, including `sub`.

    Raises:
        jwt.InvalidTokenError: On any signature/claim/hash validation failure.
    """
    settings = get_settings()
    header = jwt.get_unverified_header(id_token)
    alg = header.get("alg")
    if alg not in _ALLOWED_ALGS:
        raise jwt.InvalidTokenError(f"Unsupported id_token alg: {alg!r}")

    signing_key = await _resolve_signing_key(header.get("kid"))
    claims = jwt.decode(
        id_token,
        key=signing_key,
        algorithms=_ALLOWED_ALGS,
        audience=settings.cf_oauth_client_id,
        issuer=settings.cf_oauth_issuer,
        leeway=settings.access_token_skew,
        options={"require": ["exp", "iat"]},
    )

    if claims.get("nonce") != nonce:
        raise jwt.InvalidTokenError("id_token nonce mismatch")

    for hash_claim, source in (("at_hash", access_token), ("c_hash", code)):
        claim_value = claims.get(hash_claim)
        if claim_value is None:
            continue
        if not isinstance(claim_value, str) or not claim_value:
            raise jwt.InvalidTokenError(f"id_token {hash_claim} is malformed")
        if source is None:
            raise jwt.InvalidTokenError(
                f"id_token carries {hash_claim} but no value was provided to verify it"
            )
        expected = _compute_oidc_hash(source, alg)
        if not hmac.compare_digest(expected, claim_value):
            raise jwt.InvalidTokenError(f"id_token {hash_claim} mismatch")

    return claims


async def fetch_userinfo(access_token: str) -> dict:
    """Fetch the OIDC userinfo document for the authenticated user.

    Args:
        access_token(str): A valid Cloudflare OAuth access token.

    Return:
        userinfo(dict): The userinfo claims (at minimum `sub`).
    """
    settings = get_settings()
    headers = {"Authorization": f"Bearer {access_token}"}
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{settings.cf_oauth_issuer}/oauth2/userinfo", headers=headers)
    response.raise_for_status()
    return response.json()


async def discover_dns_scope() -> list[str]:
    """Discover the available Cloudflare OAuth scope literals.

    Return:
        scopes(list[str]): The scope literal names Cloudflare currently exposes.
    """
    settings = get_settings()
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{settings.upstream_base_url}/client/v4/oauth/scopes")
    response.raise_for_status()
    body = response.json()
    result = body.get("result", []) if isinstance(body, dict) else body
    scopes: list[str] = []
    for item in result:
        if isinstance(item, str):
            scopes.append(item)
        elif isinstance(item, dict):
            scopes.append(str(item.get("scope") or item.get("name") or item))
        else:
            scopes.append(str(item))
    return scopes
